plugins{
    id 'library.deps-conventions'
    id 'library.java-conventions'

    // The following plugin is used to build the OSGI bundle
    id 'biz.aQute.bnd.builder' version '6.4.0'
}

configurations {
    windows_x64
}

repositories {
    mavenCentral()
}

dependencies {
    api(project(':wrims-core'))
    implementation project(':third-party')

    compileOnly fileTree(dir: '../eclipse-luna-libs', include: ['*.jar'])

    windows_x64("mil.army.usace.hec:javaHeclib:${libs.versions.heclib.get()}@zip")
    testImplementation("io.cucumber:cucumber-java:7.14.0")
    testImplementation("io.cucumber:cucumber-junit-platform-engine:7.14.0")
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit.platform:junit-platform-suite")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.3")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.11.3")
    testImplementation(libs.bundles.junit5)
    testImplementation("org.eclipse.platform:org.eclipse.jface:3.35.100") // Or the appropriate version
    testImplementation("org.eclipse.platform:org.eclipse.swt:3.128.0") // Example for Windows 64-bit, choose appropriate platform
}

jar {
    bundle {
        // Bundle plugin does not properly declare dependency on Java configurations,
        // so other projects do not generate jars before the bundle plugin tries to read them.
        // The bundle plugin cannot read non-existent jars, so force an explicit dependency here
        // so that the jars will be built before the Bundle process tries to read them.
        dependsOn(configurations.runtimeClasspath)
    }
}

configurations.configureEach {
    exclude group: "javax.media", module: "jai_core"
    exclude group: "javax.media", module: "jai_codec"
    exclude group: "com.sun.media", module: "jai_imageio"
}


//task to download native libraries (dlls)
tasks.register('getNatives', Sync) { syncTask ->
    syncTask.from configurations.windows_x64.collect { zipTree(it) }
    syncTask.into file("${layout.buildDirectory.asFile.get()}/lib")
}

test {
    useJUnitPlatform()
    dependsOn(getNatives)
    systemProperty "java.library.path", "${layout.buildDirectory.asFile.get()}/lib"
}

/*
configurations {
    cucumberRuntime {
        extendsFrom testImplementation
    }
}
		
task cucumberCli() {
    dependsOn assemble, testClasses
    doLast {
        javaexec {
            main = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = [
              	'--plugin', 'pretty',
              	'--plugin', 'html:target/cucumber-report.html', 
              	'--glue', 'com.baeldung.cucumber', 
              	'src/main/java/wrimsv2_plugin/features/launch']
        }
    }
}
*/