@startuml
left to right direction
skinparam linetype ortho

component wrims_core as "WRIMS-Core" {
    package main #orange
    package serial #orange
    package wrimsv2 #orange {
        package commondata #white {
            package solverdata
            package talbledata
            package wresldata
            }
        package components
        package config
        package debug
        package evaluator #yellow
        package exception #pink
        package external
        package hdf5
        package ilp
        package launch
        package parallel
        package solver #white {
            package cbc
            package clp
            package Gurobi
            package mpmodel
            package ortools
        }
        package sql #white {
            package socket
        }
        package tf #pink
        package tools #white {
            package solutionRangeFinder
        }
        package wreslparser #white {
            package wreslparser.elements
            package wreslparser.grammar #lightseagreen
        }
        package wreslplus #white {
            package wreslplus.elements
            package wreslplus.grammar #lightseagreen
        }
    }
}

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
solver -d[hidden]-> commondata
tf -d[hidden]-> exception

footer "orange components are modules located outside the wrimsv2 package \n pink components do not rely on other packages within WRIMS-Core \n turquoise components are generated source code \n yellow packages are made up of written and generated Java code"

@enduml
