@startuml
left to right direction
skinparam linetype ortho
component wrims_core as "WRIMS-Core" {
    package wrimsv2  #orange{
        package components #lightgreen
        package commondata
        package wreslparser.elements
        package wreslplus.elements
        package solver
        package sql
        package tools
        package config
        package debug
        package evaluator #yellow
        package parallel
        package external
        package hdf5
        package ilp
        package launch
    }
package main #orange
}

components --> commondata #firebrick
commondata --> components #firebrick

components --> config #firebrick
config --> components #firebrick

components --> debug #firebrick
debug --> components #firebrick

components --> evaluator #firebrick
evaluator --> components #firebrick

components --> external #firebrick
external --> components #firebrick

components --> parallel #firebrick
parallel --> components #firebrick

components --> hdf5 #firebrick
hdf5 --> components #firebrick

components --> ilp #firebrick
ilp --> components #firebrick

components --> launch #firebrick
launch --> components #firebrick

components --> solver #firebrick
solver --> components #firebrick

components --> sql #firebrick
sql --> components #firebrick

components --> tools #firebrick
tools --> components #firebrick

components --> wreslparser.elements #firebrick
wreslparser.elements --> components #firebrick

components --> wreslplus.elements #firebrick
wreslplus.elements --> components #firebrick


main -right-> components #grey


' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
main -up[hidden]-> wrims_core
'commondata -up[hidden]-> wreslparser.elements
'wreslparser.elements -up[hidden]-> wreslplus.elements
'commondata -left[hidden]-> components
wreslparser.elements -left[hidden]-> components
wreslplus.elements -left[hidden]-> components
footer "green components indicate the primary module being represented \n orange components indicate key local modules \n red lines represent circular dependencies \n grey lines represent non-circular dependencies on 'components' \n yellow packages are made up of written and generated Java code"
@enduml
