@startuml
left to right direction
skinparam linetype ortho

component wrims_core as "WRIMS-Core" #orange {
    package wrimsv2 #white {
        package tf #lightgreen
    }
}


footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
