@startuml
left to right direction
skinparam linetype ortho

rectangle wrims_core as "WRIMS-Core" #orange {
        package wrimsv2{
            package sql {
                component sql #lightgreen {
                    package wrimsv2.sql{
                        package wrimsv2.sql.socket
                    }
                }
            }
        }
        package components
        package evaluator
        package hdf5
        package tools
        package wreslparser.elements

        package elements
}

sql -->  components
components --> sql

sql -->  evaluator
sql --> hdf5
sql --> tools
sql -r->  wreslparser.elements

elements --> sql
hdf5 --> sql

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
'debug -r[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
