@startuml
left to right direction
skinparam linetype ortho

rectangle wrims_core as "WRIMS-Core" #orange {
        package wrimsv2{
            package tools {
                component tools #lightgreen {
                    package wrimsv2.tools{
                        package wrimsv2.tools.solutionRangeFinder
                    }
                }
            }
        package commondata
        package components
        package evaluator
        package solver
        package wreslparser.elements
        package wreslparser.grammar
        package wreslplus.elements

        package hdf5
        package parallel
        package sql
    }
}

tools -u->  components #blue
components -->  tools #grey
tools -l->  evaluator #blue
evaluator -->  tools #grey
tools -u->  solver #blue
solver -->  tools #grey
tools -r->  wreslparser.elements #blue
wreslparser.elements -l->  tools #grey

tools -u->  commondata #blue
tools -u-> wreslparser.grammar #blue
tools -u-> wreslplus.elements #blue

hdf5 -u->  tools #grey
parallel -u-> tools #grey
sql -u-> tools #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
components -u[hidden]-> evaluator
commondata -u[hidden]-> solver
'solver -r[hidden]-> wreslparser.elements
'hdf5 -l[hidden]->  solver
'parallel -l[hidden]-> hdf5
'sql -l[hidden]-> parallel

footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
