@startuml
left to right direction
skinparam linetype ortho

rectangle wrims_core as "WRIMS-Core" #orange {
    package wrimsv2 {
        component commondata #lightgreen {
            package wrimsv2.commondata{
                package tabledata
                package solverdata
                package wresldata
            }
        }
        package debug
        package evaluator
        package parallel
        package components
        package hdf5
        package ilp
        package solver
        package tools

    }
package main
}

wresldata --> parallel #blue
debug --> wresldata #grey
solverdata -l-> wresldata #blue
evaluator --> solverdata #grey
solverdata -r-> evaluator #blue
wresldata --> evaluator #blue
evaluator --> wresldata #grey
wresldata --> components #blue
components --> wresldata #grey
hdf5 -d-> solverdata #grey
hdf5 -d-> wresldata #grey
ilp --> solverdata #grey
ilp --> wresldata #grey
solver --> wresldata #grey
solver --> solverdata #grey
tools --> wresldata #grey
tools --> solverdata #grey
main --> wresldata #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
' solverdata -l[hidden]-> wresldata
components -l[hidden] wrimsv2.commondata
evaluator -d[hidden]-> tabledata
evaluator -l[hidden]-> wrimsv2.commondata

footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
