@startuml
left to right direction
skinparam linetype ortho

rectangle wrims_core as "WRIMS-Core" #orange {
        package wrimsv2{
            package launch {
                component launch #lightgreen {
                    package wrimsv2.launch
                }
            }
        package components
        package evaluator
        package solver
        package hdf5
        package ilp
        package wreslparser.elements

    }
}

launch -->  components
components --> launch

launch -left->  evaluator
launch -left->  ilp
launch -left->  solver

launch -r->  wreslparser.elements

hdf5 --> launch

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
'debug -r[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
