@startuml
left to right direction
skinparam linetype ortho

component wrims_core as "WRIMS-Core" {
    package wrimsv2 #orange{
        package debug #lightgreen
    package commondata
    package components
    package evaluator #yellow
    package external
    package solver
    package wreslparser.elements
}

debug -->  components #firebrick
components -->  debug #firebrick

debug -->  commondata #blue
debug -->  evaluator #blue
debug -->  external #blue
debug -->  solver #blue
debug -->  wreslparser.elements #blue

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
'debug -r[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n red lines represent circular dependencies \n blue lines represent dependencies of 'debug' on other packages \n yellow packages are made up of written and generated Java code"
@enduml
