@startuml
left to right direction
skinparam linetype ortho

rectangle wrims_core as "WRIMS-Core" #orange {
    package wrimsv2 {
        component evaluator #lightgreen {
            package wrimsv2.evaluator{
            }
        }
        package commondata{
                package wresldata
                package solverdata

        }
        package components
        package config
        package debug
        package external
        package launch
        package parallel
        package hdf5
        package ilp
        package solver
        package sql
        package tools

    }
package main
}

evaluator --> components #blue
components --> evaluator #grey
evaluator --> hdf5 #blue
hdf5 --> evaluator  #grey
evaluator --> ilp #blue
ilp --> evaluator  #grey
evaluator --> solver #blue
solver -left-> evaluator  #grey
evaluator --> tools #blue
tools --> evaluator  #grey

evaluator --> external #blue
evaluator --> parallel #blue
evaluator --> solverdata #blue
evaluator --> wresldata #blue

config --> evaluator  #grey
debug --> evaluator  #grey
launch --> evaluator  #grey
sql --> evaluator  #grey
main -l-> evaluator  #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
components -up[hidden]-> ilp
ilp -up[hidden]-> hdf5
hdf5 -up[hidden]-> solver
solver -up[hidden]-> tools

footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
