@startuml
left to right direction
skinparam linetype ortho

component wrims_core as "WRIMS-Core" {
    package wrimsv2 #orange {
        package hdf5 #lightgreen
        package commondata
        package components
        package config
        package evaluator #yellow
        package launch
        package parallel
        package tools
        package sql
    }
}
package main #orange

hdf5 -left->  components #firebrick
components -->  hdf5 #firebrick
hdf5 -left->  evaluator #firebrick
evaluator -->  hdf5 #firebrick

hdf5 -right->  sql #blue
hdf5 -l->  commondata #blue
hdf5 -->  config #blue
hdf5 -->  launch #blue
hdf5 -l->  parallel #blue
hdf5 -->  tools #blue
main --> hdf5 #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
'debug -r[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n red lines represent circular dependencies \n blue lines represent dependencies of 'hdf5' on other packages \n grey lines represent non-circular dependencies on 'hdf5' \n yellow packages are made up of written and generated Java code"
@enduml
