@startuml
left to right direction
skinparam linetype ortho

component wrims_core as "WRIMS-Core" {
    package wrimsv2  #orange{
        package external #lightgreen
        package components
        package config
        package debug
        package evaluator #yellow
        package ilp
    }
}

components -r-> external #firebrick
external -l-> components #firebrick

evaluator -r-> external #firebrick
external -l-> evaluator #firebrick

external -r-> ilp #blue
external --> config #blue

debug -> external #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
components -u[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n red lines represent circular dependencies \n blue lines represent dependencies of 'external' on other packages \n grey lines represent non-circular dependencies on 'external' \n yellow packages are made up of written and generated Java code"
@enduml
