@startuml
left to right direction
skinparam linetype ortho

rectangle wrims_core as "WRIMS-Core" #orange {
        package wrimsv2{
            package ilp {
                component ilp #lightgreen {
                    package wrimsv2.ilp
                }
            }
        package commondata
        package components
        package evaluator
        package solver
        package tools
        package wreslparser.elements

        package config
        package external
        package launch
    }
package main
}

ilp -->  components #blue
components -left->  ilp #grey
ilp -left->  evaluator #blue
evaluator -->  ilp #grey
ilp -left->  solver #blue
solver -->  ilp #grey

ilp -->  commondata #blue
ilp -->  tools #blue
ilp -r->  wreslparser.elements #blue

config --> ilp #grey
external --> ilp #grey
launch --> ilp #grey

main --> ilp #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
'debug -r[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
