@startuml
left to right direction
skinparam linetype ortho

rectangle wrims_core as "WRIMS-Core" #orange {
        package wrimsv2{
            package wreslparser.elements {
                component wreslparser.elements #lightgreen {
                    package wrimsv2.wreslparser.elements
                }
            }
        package commondata
        package components
        package evaluator
        package solver
        package tools
        package sql
        package wreslparser.grammar
        package wreslplus.elements

        package config
        package debug
        package hdf5
        package ilp
        package launch
    }
package main
}

wreslparser.elements -l->  components #blue
components -->  wreslparser.elements #grey
wreslparser.elements -l->  solver #blue
solver -->  wreslparser.elements #grey
wreslparser.elements -l->  tools #blue
tools -->  wreslparser.elements #grey
wreslparser.elements -l->  wreslplus.elements #blue
wreslplus.elements -->  wreslparser.elements #grey

wreslparser.elements -r->  commondata #blue
wreslparser.elements -r->  evaluator #blue
wreslparser.elements -r->  sql #blue
wreslparser.elements -r->  wreslparser.grammar #blue

config -->  wreslparser.elements #grey
debug -->  wreslparser.elements #grey
hdf5 -->  wreslparser.elements #grey
ilp -->  wreslparser.elements #grey
launch -->  wreslparser.elements #grey
main --> wreslparser.elements #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
'debug -r[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
