@startuml
left to right direction
skinparam linetype ortho
rectangle wrims_core as "WRIMS-Core" #orange {
    package wrimsv2 {
        component components #lightgreen {
            package wrimsv2.components
        }
        package commondata
        package wreslparser.elements
        package wreslplus.elements
        package solver
        package sql
        package tools
        package config
        package debug
        package evaluator
        package external
        package hdf5
        package ilp
        package launch
    }
package main
}

components --> commondata #blue
commondata --> components #grey

components --> config #blue
config --> components #grey

components --> debug #blue
debug --> components #grey

components --> evaluator #blue
evaluator --> components #grey

components --> external #blue
external --> components #grey

components --> hdf5 #blue
hdf5 --> components #grey

components --> ilp #blue
ilp --> components #grey

components --> launch #blue
launch --> components #grey

components --> solver #blue
solver --> components #grey

components --> sql #blue
sql --> components #grey

components --> tools #blue
tools --> components #grey

components --> wreslparser.elements #blue
wreslparser.elements --> components #grey

components --> wreslplus.elements #blue
wreslplus.elements --> components #grey


main -right-> components #grey


' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
main -up[hidden]-> wrims_core
'commondata -up[hidden]-> wreslparser.elements
'wreslparser.elements -up[hidden]-> wreslplus.elements
'commondata -left[hidden]-> components
wreslparser.elements -left[hidden]-> components
wreslplus.elements -left[hidden]-> components
footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
