@startuml
left to right direction
skinparam linetype ortho

component wrims_core as "WRIMS-Core"{
    package wrimsv2 #orange {
        package solver #lightgreen {
            package cbc
            package clp
            package Gurobi
            package mpmodel
            package ortools
        }
        package commondata
        package components
        package evaluator #yellow
        package ilp
        package tools
        package wreslparser.elements
        package config
        package debug
        package launch
    }
}

solver -left->  components #firebrick
components -left-> solver #firebrick
solver -left->  evaluator #firebrick
evaluator -r-> solver #firebrick
solver -left->  ilp #firebrick
ilp --> solver #firebrick
solver -left->  tools #firebrick
tools --> solver #firebrick
solver -left->  wreslparser.elements #firebrick
wreslparser.elements --> solver #firebrick

solver -left->  commondata #blue

config --> solver #grey
debug --> solver #grey
launch --> solver #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
'debug -r[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n red lines represent circular dependencies \n blue lines represent dependencies of 'solver' on other packages \n grey lines represent non-circular dependencies on 'solver' \n yellow packages are made up of written and generated Java code"
@enduml
