@startuml
left to right direction
skinparam linetype ortho

rectangle wrims_core as "WRIMS-Core" #orange {
        package wrimsv2{
            package hdf5 {
                component hdf5 #lightgreen {
                    package wrimsv2.hdf5
                }
            }
        package commondata
        package components
        package config
        package evaluator
        package launch
        package parallel
        package solver
        package tools
        package wreslparser.elements
        package sql
    }
}
package main #orange

hdf5 -left->  components #blue
components -->  hdf5 #grey
hdf5 -left->  evaluator #blue
evaluator -->  hdf5 #grey
sql -left->  hdf5 #grey
hdf5 -right->  sql #blue

hdf5 -->  commondata #blue
hdf5 -->  config #blue
hdf5 -->  launch #blue
hdf5 -->  parallel #blue
hdf5 -->  solver #blue
hdf5 -->  tools #blue
hdf5 -->  wreslparser.elements #blue
main --> hdf5 #grey

' The following relationships are hidden and used to format the diagram. They do not represent actual dependencies.
'debug -r[hidden]-> evaluator

footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
