@startuml
left to right direction
skinparam linetype ortho

component wrims_core as "WRIMS-Core" {
    package wrimsv2 #orange {
        package exception #lightgreen
    }
}


footer "green components indicate the primary module being represented \n orange components indicate key local modules"
@enduml
