/*
 * generated by Xtext
 */
package gov.ca.dwr.wresl.xtext.editor.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class WreslEditorScopeProvider extends AbstractDeclarativeScopeProvider {

	@Override
	protected IScope delegateGetScope(EObject context, EReference reference) {
		// TODO Auto-generated method stub
		return super.delegateGetScope(context, reference);
	}

	@Override
	public IScope getScope(EObject context, EReference reference) {
		// TODO Auto-generated method stub
		return super.getScope(context, reference);
	}

}
