      SUBROUTINE CHRWT (KLFN,CSTR2,NSTR2)
      CHARACTER*(*) CSTR2
C     WRITE CHARACTERS TO UNIT KLFN
      IF (NSTR2.LE.0) return
c
      WRITE (KLFN, 10) CSTR2(1:NSTR2)
 10   FORMAT (A)
C
      RETURN
      END
