start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd EXISTING_BO__(LpSolve_vs_XA).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd EXISTING_PREBO__(LpSolve_vs_XA).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd FUTURE_BO__(LpSolve_vs_XA).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd FUTURE_PREBO__(LpSolve_vs_XA).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd preMod_EXISTING_BO__(LpSolve_vs_XA).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd preMod_EXISTING_PREBO__(LpSolve_vs_XA).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd preMod_FUTURE_BO__(LpSolve_vs_XA).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd preMod_FUTURE_PREBO__(LpSolve_vs_XA).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd XA_EXISTING_BO__(preMod_vs_postMod).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd XA_EXISTING_PREBO__(preMod_vs_postMod).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd XA_FUTURE_BO__(preMod_vs_postMod).inp
start /wait D:\cvwrsm\callite-report-tool\callite_report_batch.cmd XA_FUTURE_PREBO__(preMod_vs_postMod).inp