/*
 * generated by Xtext
 */
package gov.ca.dwr.wresl.xtext.editor.ui.outline;

import gov.ca.dwr.wresl.xtext.editor.wreslEditor.Alias;
import gov.ca.dwr.wresl.xtext.editor.wreslEditor.Define;
import gov.ca.dwr.wresl.xtext.editor.wreslEditor.Goal;
import gov.ca.dwr.wresl.xtext.editor.wreslEditor.IncludeFile;
import gov.ca.dwr.wresl.xtext.editor.wreslEditor.Model;
import gov.ca.dwr.wresl.xtext.editor.wreslEditor.Objective;
import gov.ca.dwr.wresl.xtext.editor.wreslEditor.Sequence;
import gov.ca.dwr.wresl.xtext.editor.wreslEditor.WreslEvaluator;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class WreslEditorOutlineTreeProvider extends DefaultOutlineTreeProvider {
	@Override
	protected void _createNode(IOutlineNode parentNode, EObject modelElement) {
		if (modelElement instanceof WreslEvaluator
				|| modelElement instanceof Model
				|| modelElement instanceof Sequence
				|| modelElement instanceof IncludeFile
				|| modelElement instanceof Define
				|| modelElement instanceof Alias
				|| modelElement instanceof Goal
				|| modelElement instanceof Objective) {
			super._createNode(parentNode, modelElement);
		}
	}

	public boolean _isLeaf(EObject modelElement) {
		return !(modelElement instanceof WreslEvaluator || modelElement instanceof Model);
	}

}
