/*
 * generated by Xtext
 */
package gov.ca.dwr.wresl.xtext.editor.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.ImportUriValidator.class})
public class AbstractWreslEditorJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(gov.ca.dwr.wresl.xtext.editor.wreslEditor.WreslEditorPackage.eINSTANCE);
		return result;
	}

}
