/*
 * generated by Xtext
 */
package gov.ca.dwr.wresl.xtext.editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WreslEditorUiModule extends gov.ca.dwr.wresl.xtext.editor.ui.AbstractWreslEditorUiModule {
	public WreslEditorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

}
