/*
 * generated by Xtext
 */
package gov.ca.dwr.wresl.xtext.editor;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WreslEditorRuntimeModule extends gov.ca.dwr.wresl.xtext.editor.AbstractWreslEditorRuntimeModule {
	public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
		return WreslTerminalConverters.class;
	}


}
