/*
* generated by Xtext
*/
package gov.ca.dwr.wresl.xtext.editor.ui.contentassist;

import gov.ca.dwr.wresl.xtext.editor.ui.contentassist.AbstractWreslEditorProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WreslEditorProposalProvider extends AbstractWreslEditorProposalProvider {

}
