/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wrimsv2_external_FunctionAnn_X2 */

#ifndef _Included_wrimsv2_external_FunctionAnn_X2
#define _Included_wrimsv2_external_FunctionAnn_X2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wrimsv2_external_FunctionAnn_X2
 * Method:    Ann_X2
 * Signature: (FFFFFFFFFFIIIIIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_wrimsv2_external_FunctionAnn_1X2_Ann_1X2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
