/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wrimsv2_external_FunctionAnnLineGen */

#ifndef _Included_wrimsv2_external_FunctionAnnLineGen
#define _Included_wrimsv2_external_FunctionAnnLineGen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wrimsv2_external_FunctionAnnLineGen
 * Method:    AnnLineGen
 * Signature: (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFIIIIIFFFIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_wrimsv2_external_FunctionAnnLineGen_AnnLineGen
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
