/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wrimsv2_external_FunctionAnnEC */

#ifndef _Included_wrimsv2_external_FunctionAnnEC
#define _Included_wrimsv2_external_FunctionAnnEC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wrimsv2_external_FunctionAnnEC
 * Method:    AnnEC
 * Signature: (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFIIIIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_wrimsv2_external_FunctionAnnEC_AnnEC
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
