@startuml

!theme plain
left to right direction
skinparam linetype ortho

component wrims_core as "wrims-core" #lightgreen
component ST4
component XAOptimizer as "XAOptimizer.jar" #lightblue
component antlr
component antlr_runtime as "antlr-runtime"
component apiguardian_api as "apiguardian-api"
component autocomplete
component bcpkix_jdk15on as "bcpkix-jdk15on"
component bcprov_jdk15on as "bcprov-jdk15on"
component bsh
component callback_services as "callback-services"
component calsurrogate as "calsurrogate.jar" #lightblue
component checker_compat_qual as "checker-compat-qual"
component coinor as "coinor.jar" #lightblue
component linearsolver as "com.google.ortools.linearsolver.jar" #lightblue
component commons_codec as "commons-codec"
component commons_io as "commons-io"
component commons_lang as "commons-lang"
component commons_logging as "commons-logging"
component callback_services7 as "commons-vfs2"
component dom4j
component error_prone_annotations
component flogger
component guava
component gurobi as "gurobi.jar" #lightblue
component monolith as "hec-monolith"
component nucleus_data as "hec-nucleus-data"
component nucleus_metadata as "hec-nucleus-metadata"
component jackson_annotations as "jackson-annotations"
component callback_services9 as "jackson-core"
component jackson_databind as "jackson-databind"
component jarhdf5 as "jarhdf5-2.11.0.jar" #lightblue
component java_object_diff as "java-object-diff"
component javahelp
component javatuples
component jcommander
component jcommon
component jdom
component jep
component jfreechart
component jmscommon
component jna
component jsr305
component jts
component junit
component junit_bom as "junit-bom"
component junit_jupiter_api as "junit-jupiter-api"
component junit_engine as "junit-jupiter-engine"
component junit_params as "junit-jupiter-params"
component junit_commons as "junit-platform-commons"
component junit_engine as "junit-platform-engine"
component jython as "jython-standalone"
component kryo
component libtensorflow
component lookup
component lpsolve55j as "lpsolve55j.jar" #lightblue
component minlog
component mrsidreader
component objenesis
component opentest4j
component poi
component poi_ooxml as "poi-ooxml"
component poi_ooxml_schemas as "poi-ooxml-schemas"
component rstaui
component rsyntaxtextarea
component service_annotations as "service-annotations"
component snakeyaml
component stax_api as "stax-api"
component swingx_action as "swingx-action"
component swingx_autocomplete as "swingx-autocomplete"
component swingx_common as "swingx-common"
component swingx_core as "swingx-core"
component swingx_graphics as "swingx-graphics"
component swingx_painters as "swingx-painters"
component swingx_plaf as "swingx-plaf"
component testng
component vrt
component xml_apis as "xml-apis"
component xmlbeans
component xmlpull
component xpp3_min
component xstream

wrims_core                   -[#000082,plain]->  XAOptimizer             
wrims_core                   -[#000082,plain]->  antlr                   
wrims_core                   -[#000082,plain]->  calsurrogate            
wrims_core                   -[#000082,plain]->  coinor                  
wrims_core                   -[#000082,plain]->  linearsolver                  
wrims_core                   -[#000082,plain]->  commons_io                  
wrims_core                   -[#000082,plain]->  guava                   
wrims_core                   -[#000082,plain]->  gurobi                  
wrims_core                   -[#000082,plain]->  monolith                  
wrims_core                   -[#000082,plain]->  nucleus_metadata                  
wrims_core                   -[#000082,plain]->  jarhdf5                  
wrims_core                   -[#000082,plain]->  java_object_diff                  
wrims_core                   -[#000082,plain]->  javatuples              
wrims_core                   -[#000082,plain]->  jep                     
wrims_core                   -[#000082,plain]->  junit_jupiter_api                  
wrims_core                   -[#000082,plain]->  junit_engine                  
wrims_core                   -[#000082,plain]->  junit_params                  
wrims_core                   -[#000082,plain]->  kryo                    
wrims_core                   -[#000082,plain]->  libtensorflow           
wrims_core                   -[#000082,plain]->  lpsolve55j              
wrims_core                   -[#000082,plain]->  testng                  
wrims_core                   -[#000082,plain]->  xstream                 
ST4                      -[#000082,plain]->  antlr_runtime                  
antlr                    -[#000082,plain]->  ST4                     
antlr                    -[#000082,plain]->  antlr_runtime                  
autocomplete             -[#000082,plain]->  rsyntaxtextarea         
bcpkix_jdk15on                    -[#000082,plain]->  bcprov_jdk15on                  
callback_services                    -[#000082,plain]->  jackson_annotations                  
callback_services                    -[#000082,plain]->  callback_services9                  
callback_services                    -[#000082,plain]->  jackson_databind                   
callback_services                    -[#000082,plain]->  lookup                  
callback_services                    -[#000082,plain]->  service_annotations                  
callback_services7                   -[#000082,plain]->  commons_logging                  
dom4j                    -[#000082,plain]->  xml_apis                   
flogger                  -[#000082,plain]->  checker_compat_qual                  
guava                    -[#000082,plain]->  jsr305                  
monolith                   -[#000082,plain]->  bcpkix_jdk15on                   
monolith                   -[#000082,plain]->  bcprov_jdk15on                  
monolith                   -[#000082,plain]->  callback_services                   
monolith                   -[#000082,plain]->  commons_lang                  
monolith                   -[#000082,plain]->  callback_services7                  
monolith                   -[#000082,plain]->  error_prone_annotations 
monolith                   -[#000082,plain]->  flogger                 
monolith                   -[#000082,plain]->  nucleus_data                  
monolith                   -[#000082,plain]->  nucleus_metadata                  
monolith                   -[#000082,plain]->  jackson_annotations                  
monolith                   -[#000082,plain]->  javahelp                
monolith                   -[#000082,plain]->  jcommon                 
monolith                   -[#000082,plain]->  jfreechart              
monolith                   -[#000082,plain]->  jmscommon               
monolith                   -[#000082,plain]->  jna                     
monolith                   -[#000082,plain]->  jsr305                  
monolith                   -[#000082,plain]->  jts                     
monolith                   -[#000082,plain]->  jython                  
monolith                   -[#000082,plain]->  lookup                  
monolith                   -[#000082,plain]->  mrsidreader             
monolith                   -[#000082,plain]->  poi                     
monolith                   -[#000082,plain]->  poi_ooxml                   
monolith                   -[#000082,plain]->  rstaui                  
monolith                   -[#000082,plain]->  service_annotations                  
monolith                   -[#000082,plain]->  swingx_core                  
monolith                   -[#000082,plain]->  vrt                     
nucleus_data                   -[#000082,plain]->  nucleus_metadata                  
nucleus_metadata                   -[#000082,plain]->  jdom                    
nucleus_metadata                   -[#000082,plain]->  lookup                  
nucleus_metadata                   -[#000082,plain]->  service_annotations                  
jfreechart               -[#000082,plain]->  jcommon                 
junit_bom                   -[#000082,plain]->  junit_jupiter_api                  
junit_bom                   -[#000082,plain]->  junit_engine                  
junit_bom                   -[#000082,plain]->  junit_params                  
junit_bom                   -[#000082,plain]->  junit_commons                  
junit_bom                   -[#000082,plain]->  junit_engine                  
junit_jupiter_api                   -[#000082,plain]->  apiguardian_api                  
junit_jupiter_api                   -[#000082,plain]->  junit_bom                  
junit_jupiter_api                   -[#000082,plain]->  junit_commons                  
junit_jupiter_api                   -[#000082,plain]->  opentest4j              
junit_engine                   -[#000082,plain]->  apiguardian_api                  
junit_engine                   -[#000082,plain]->  junit_bom                  
junit_engine                   -[#000082,plain]->  junit_jupiter_api                  
junit_engine                   -[#000082,plain]->  junit_engine                  
junit_params                   -[#000082,plain]->  apiguardian_api                  
junit_params                   -[#000082,plain]->  junit_bom                  
junit_params                   -[#000082,plain]->  junit_jupiter_api                  
junit_commons                   -[#000082,plain]->  apiguardian_api                  
junit_commons                   -[#000082,plain]->  junit_bom                  
junit_engine                   -[#000082,plain]->  apiguardian_api                  
junit_engine                   -[#000082,plain]->  junit_bom                  
junit_engine                   -[#000082,plain]->  junit_commons                  
junit_engine                   -[#000082,plain]->  opentest4j              
kryo                     -[#000082,plain]->  minlog                  
kryo                     -[#000082,plain]->  objenesis               
poi                      -[#000082,plain]->  commons_codec                  
poi_ooxml                    -[#000082,plain]->  dom4j                   
poi_ooxml                    -[#000082,plain]->  poi                     
poi_ooxml                    -[#000082,plain]->  poi_ooxml_schemas                  
poi_ooxml_schemas                   -[#000082,plain]->  xmlbeans                
rstaui                   -[#000082,plain]->  autocomplete            
rstaui                   -[#000082,plain]->  rsyntaxtextarea         
swingx_autocomplete                   -[#000082,plain]->  swingx_common                  
swingx_core                   -[#000082,plain]->  swingx_action                  
swingx_core                   -[#000082,plain]->  swingx_autocomplete                  
swingx_core                   -[#000082,plain]->  swingx_graphics                  
swingx_core                   -[#000082,plain]->  swingx_painters                  
swingx_core                   -[#000082,plain]->  swingx_plaf                  
swingx_graphics                   -[#000082,plain]->  swingx_common                  
swingx_painters                   -[#000082,plain]->  swingx_common                  
swingx_plaf                   -[#000082,plain]->  swingx_common                  
testng                   -[#000082,plain]->  bsh                     
testng                   -[#000082,plain]->  jcommander              
testng                   -[#000082,plain]->  junit                   
testng                   -[#000082,plain]->  snakeyaml               
xmlbeans                 -[#000082,plain]->  stax_api                  
xstream                  -[#000082,plain]->  xmlpull                 
xstream                  -[#000082,plain]->  xpp3_min

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n blue components indicate locally-stored third-party jars"

@enduml
