@startuml
'https://plantuml.com/component-diagram
header "WRIMS"
left to right direction
skinparam linetype ortho
cloud hec_nexus as "HEC Nexus"
cloud maven_central as "Maven Central"

rectangle wrims as "WRIMS 2.2"{
    rectangle wrims_ide as "WRIMS IDE" #lightgreen

    rectangle wrims_dssvue as "DWR DSSVue" #orange {
        package dssvue as "gov.ca.dwr.hecdssvue"
    }

    rectangle wrims_jdiagram as "DWR JDiagram" #orange {
        package gov.ca.dwr.jdiagram
    }

    rectangle wrims_core as "WRIMS Core" #orange

    package xtext_editor as "gov.ca.dwr.xtext.editor" #orange

    package xtext_editor_ui as "gov.ca.dwr.xtext.editor.ui" #orange

    rectangle eclipse_luna_libs as "Eclipse Luna Libraries" #orange {
        package org.eclipse.xtext
    }

    rectangle third_party as "Third-Party" #orange {
        rectangle local_jars as "Local Jars" #white
        rectangle resolved_deps as "Resolved dependencies" #white {
        rectangle hec as "HEC"
        rectangle non_hec as "Non-HEC"
    }
}



wrims_ide -down-> wrims_core #blue
wrims_ide -down-> eclipse_luna_libs #blue
wrims_ide -down-> local_jars #grey
wrims_ide -down-> hec #grey
wrims_ide -down-> wrims_dssvue #blue
wrims_ide -> xtext_editor_ui #blue
wrims_ide -down-> non_hec #grey
wrims_ide -down-> wrims_jdiagram #blue

wrims_core -down-> local_jars #grey
wrims_core -down-> non_hec #grey
wrims_core -down-> hec #grey

xtext_editor_ui -down-> xtext_editor #blue
xtext_editor_ui -down-> local_jars #grey
xtext_editor_ui -down-> non_hec #grey
xtext_editor -down-> local_jars #grey
xtext_editor -> eclipse_luna_libs #blue
xtext_editor_ui -> eclipse_luna_libs #blue


gov.ca.dwr.jdiagram -> local_jars #grey
wrims_jdiagram -> eclipse_luna_libs #blue

hec -down-> hec_nexus
non_hec -down-> maven_central

dssvue -> hec #grey
dssvue -> local_jars #grey
dssvue -> eclipse_luna_libs #blue

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n blue lines indicate module-to-module dependencies"
@enduml