      SUBROUTINE ZSPD (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     * C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, CLABEL, LABEL,
     * IUHEAD, NUHEAD, IPLAN, ISTAT)
C
C     Store Paired DATA
C
C     Written by Bill Charley
C
C
      INTEGER IFLTAB(*), IUHEAD(*)
      CHARACTER CPATH*(*), CLABEL(*)*(*)
      CHARACTER C1UNIT*(*), C1TYPE*(*), C2UNIT*(*), C2TYPE*(*)
      REAL SVALUES(*)
      LOGICAL LABEL
      DOUBLE PRECISION DVALUES(1)
C
C
      CALL ZSPDI (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     * C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     * .FALSE., CLABEL, LABEL, IUHEAD, NUHEAD, IPLAN, ISTAT)
C
      END
