@startuml
'https://plantuml.com/component-diagram
cloud hec_nexus as "HEC Nexus"
cloud maven_central as "Maven Central"
cloud dwr_github as "DWR GitHub"

rectangle wrims as "WRIMS Installer"{
    package wrims_plugin as "gov.ca.dwr.wrims_plugin"{
        component wrims_core as "wrims-core.jar" #orange
        rectangle hec_dependencies #orange
        rectangle non_hec_dependencies #orange
        rectangle dwr_dependencies #orange
    }
    package wrims_dssvue as "gov.ca.dwr.hecdssvue" {
        component dssvue as "dssgui.jar"
    }
    package wrims_jdiagram as "gov.ca.dwr.jdiagram" {
        component jdiagram as "jdiagram.jar"
    }
    package wrims_xtext_editor as "gov.ca.dwr.xtext.editor" {
        component xtext as "xtext.jar" #orange
    }
    package wrims_xtext_editor_ui as "gov.ca.dwr.xtext.editor.ui"
}

wrims_core -down-> hec_dependencies
wrims_core -down-> non_hec_dependencies
wrims_core -down-> dwr_dependencies
wrims_xtext_editor_ui -down-> wrims_xtext_editor
wrims_dssvue -down-> wrims_plugin
hec_dependencies -down.-> hec_nexus
non_hec_dependencies -down.-> maven_central
dwr_dependencies -down.-> dwr_github

dssvue -down.-> hec_nexus
jdiagram -down.-> maven_central
xtext -down.-> maven_central

footer "orange components indicate exported dependencies"
@enduml