/*
 * generated by Xtext
 */
package gov.ca.dwr.wresl.xtext.editor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WreslEditorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return gov.ca.dwr.wresl.xtext.editor.ui.internal.WreslEditorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return gov.ca.dwr.wresl.xtext.editor.ui.internal.WreslEditorActivator.getInstance().getInjector("gov.ca.dwr.wresl.xtext.editor.WreslEditor");
	}
	
}
