@startuml
left to right direction
skinparam linetype ortho

component WRIMS_IDE as "WRIMS-IDE" {
    package wrimsv2_plugin {
        package debugger
        package sensitivity
        package tools
        package reporttool
        package batchrun
        package calsimhydro
        package editor
        package perspective
        package presentation
    }
}

sensitivity -> tools
sensitivity -> debugger #firebrick

calsimhydro --> debugger #firebrick

batchrun -> tools
batchrun --> debugger #firebrick

reporttool -> tools
reporttool -> debugger #firebrick

debugger -> sensitivity #firebrick
debugger -> batchrun #firebrick
debugger -> calsimhydro #firebrick
debugger -> reporttool #firebrick
debugger -> tools #firebrick

tools --> debugger #firebrick

editor -d-> debugger
perspective -> debugger
presentation -u-> debugger

footer "red lines represent circular dependencies"
@enduml
