@startuml

!theme plain
left to right direction
skinparam linetype ortho

rectangle wrims-ide as "WRIMS IDE" #orange {
    component batchrun #lightgreen {
        package wrimsv2_plugin.batchrun
    }
    component tools {
        package wrimsv2_plugin.tools
    }
    component debugger {
        package wrimsv2_plugin.debugger
    }
}

component luna_libs as "directory '../eclipse-luna-libs'" #orange
rectangle third-party #orange {
    component vista as "vista.jar" #lightblue
}

batchrun -down-> luna_libs
batchrun -down-> vista
batchrun -down-> tools
batchrun -down-> debugger

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n blue components indicate locally-stored third-party jars"
@enduml
