@startuml

!theme plain
left to right direction
skinparam linetype ortho

rectangle WRIMS {
    component wrims-ide as "WRIMS IDE" #orange {
        package wrimsv2_plugin {
            package batchrun #lightgreen
            package tools
            package debugger
        }
    }

    folder luna_libs as "directory '../eclipse-luna-libs'" #orange
    rectangle Third-Party #orange {
        component vista as "vista.jar" #lightblue
    }
}

batchrun -r-> luna_libs
batchrun -l-> vista
batchrun -down-> tools
batchrun -down-> debugger #firebrick

debugger -> batchrun #firebrick

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n blue components indicate locally-stored third-party jars \n red lines represent circular dependencies"
@enduml
