@startuml

!theme plain
left to right direction
skinparam linetype ortho

rectangle WRIMS {
    component wrims-ide as "WRIMS IDE" #orange {
        package wrimsv2_plugin {
            package tools #lightgreen
            package debugger
        }
    }

    folder luna_libs as "directory '../eclipse-luna-libs'" #orange
    rectangle third-party as "Third Party" #orange {
        package mil.army.usace.hec.metadata
    }

    component wrims-core as "WRIMS Core" #orange {
        package wrimsv2 {
            package commondata.wresldata
        }
    }
}
tools -r-> luna_libs
tools -l-> debugger #firebrick
tools -u-> mil.army.usace.hec.metadata
tools -down-> commondata.wresldata

debugger -> tools #firebrick

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n red lines represent circular dependencies"
@enduml
