@startuml

!theme plain
left to right direction
skinparam linetype ortho

rectangle WRIMS {
    component wrims-ide as "WRIMS IDE" #orange {
        package wrimsv2_plugin {
            package debugger #lightgreen
            package tools
            package batchrun
            package calsimhydro
            package reporttool
            package sensitivity
        }
    }

    component wrims_core as "WRIMS Core" #orange {
        package wrimsv2 {
            package commondata.wresldata
            package debug
            package components
        }
    }

    rectangle third-party as "Third Party" #orange {
        package org.osgi
        component javaHeclib {
            package hec.heclib.dss
        }
        component hec.monolith as "hec-monolith" {
            package hec.io
            package hec.hecmath
            package hec.gfx2d
        }
        component vista.jar #lightblue
        component commons_io as "commons-io" {
            package org.apache.commons.io
        }
    }

    folder luna_libs as "directory '../eclipse-luna-libs'" #orange
}
debugger -> luna_libs
debugger -up-> tools #firebrick
debugger --> batchrun #firebrick
debugger -> commondata.wresldata
debugger -> debug
debugger -right-> org.osgi
debugger -down-> hec.heclib.dss
debugger -up-> calsimhydro #firebrick
debugger -down-> hec.io
debugger -down-> vista.jar
debugger -down-> org.apache.commons.io
debugger -down-> components
debugger -down-> hec.hecmath
debugger --> reporttool #firebrick
debugger -down-> sensitivity #firebrick
debugger -down-> hec.gfx2d

sensitivity -> debugger #firebrick
batchrun -> debugger #firebrick
calsimhydro -u-> debugger #firebrick
tools -> debugger #firebrick
reporttool -> debugger #firebrick

footer "green components indicate the primary module being represented \n orange components indicate key local modules \n blue components indicate locally-stored third-party jars \n red lines represent circular dependencies"
@enduml
