/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Apr 6, 2011, 2:24:20 PM
 */

package wrimsv2.gui;

/**
 *
 * @author hxie
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        setSize(1024,786);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studyPanel = new wrimsv2.gui.ImportPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        editorPanel = new wrimsv2.gui.EditorPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        openStudyMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N

        tabbedPane.addTab("Import", studyPanel);
        tabbedPane.addTab("Editor", editorPanel);

        jFileMenu.setText("File");

        openStudyMenu.setText("Import Study");
        jFileMenu.add(openStudyMenu);

        mainMenuBar.add(jFileMenu);

        editMenu.setText("Edit");
        mainMenuBar.add(editMenu);

        setJMenuBar(mainMenuBar);

        add(tabbedPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private wrimsv2.gui.EditorPanel editorPanel;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem openStudyMenu;
    private wrimsv2.gui.ImportPanel studyPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
