      SUBROUTINE ZGIRTS (IFLTAB, CPATH, NPATH, JULS, ISTIME,
     * JULE, IETIME, IBUFF, KBUFF, IDUM, NDUM, KVALS, DATES, VALUES,
     * NVALS, BDATE, CUNITS, CTYPE, ISTAT)
C
C     Get Irregular Time Series data
C     Replaced by ZRITSX
C
C
      INTEGER IFLTAB(*), IBUFF(KBUFF)
      LOGICAL LQUAL
      CHARACTER CPATH*(*), CUNITS*(*), CTYPE*(*)
      REAL DATES(*), VALUES(*)
C
C
      INFLAG = 0
      IF (ISTAT.EQ.-11) INFLAG = 1
      IF (ISTAT.EQ.-12) INFLAG = 2
      IF (ISTAT.EQ.-13) INFLAG = 3
      ISTAT = 0
C
      N = NDUM
      CALL ZRITSX (IFLTAB, CPATH(1:NPATH), JULS, ISTIME, JULE, IETIME,
     * DATES, VALUES, KVALS, NVALS, IBDATE, JQUAL, .FALSE., LQUAL,
     * CUNITS, CTYPE, IUHEAD, 0, N, INFLAG, ISTAT)
C
      BDATE = IBDATE
      CALL ZMIN2R (DATES, DATES, 0.0, NVALS)
C
C
      RETURN
      END
